x = 10.0
y = 20.0
values = [ 1.0, 2.0, 3.0, 4.0, 5.0,]
result = 30.0
resultt = 310.0

[settings]
version = 10.0

[var]
endpoints = [ 6447.0, 145.0,]

[var.notifications]
email = 123.0
sms = 1234567890.0
alertthreshold = 15.0

[var.status]
lastcheck = 2024.0
isup = 1.0
responsetime = 150.0
