monitoring_service = "HealthCheckService"
check_interval = 5

[table]
endpoints = [ "http://localhost:8080/health", "http://localhost:8080/status",]
email = "\"admin@example.com\","
sms = "\"1234567890\","
alert_threshold = 15
last_check = "\"2023-10-01T12:00:00Z\","
is_up = "true,"
response_time = 200
